import Image from "next/image";
import Link from "next/link";
import { ArrowRight, GraduationIcon, HeartIcon, HeartPulseIcon, LeafIcon, ToolsIcon, UsersIcon } from "../../components/icons";

const values = [
  { title: "Compassion", text: "We see every child and widow as a person of dignity, possibility and worth.", icon: HeartIcon },
  { title: "Faith", text: "We share the good news of Jesus Christ, the soon-coming King, through preaching, love and service.", icon: "✦" },
  { title: "Integrity", text: "We steward every relationship and resource with honesty, accountability and care.", icon: "✓" },
  { title: "Empowerment", text: "We create practical pathways that help vulnerable people move from dependence toward opportunity.", icon: LeafIcon },
  { title: "Community", text: "We listen, serve and work alongside local communities for solutions that can last.", icon: UsersIcon },
  { title: "Hope", text: "We believe a brighter tomorrow is possible when people are given love, support and opportunity.", icon: "↗" },
];

const impact = [
  { title: "Education", text: "Supporting children with access to learning, school needs and a chance to dream bigger.", icon: GraduationIcon },
  { title: "Healthcare", text: "Helping vulnerable families access essential healthcare and practical wellbeing support.", icon: HeartPulseIcon },
  { title: "Empowerment", text: "Equipping widows and vulnerable households with skills and sustainable livelihood opportunities.", icon: ToolsIcon },
  { title: "Preaching & Outreach", text: "Taking love, encouragement and the good news of Jesus Christ into communities that need hope.", icon: HeartIcon },
];

export default function AboutUsPage() {
  return (
    <main className="overflow-hidden bg-white text-[#101b13]">
      <section className="about-hero relative isolate min-h-[650px] overflow-hidden bg-[#03160b] text-white lg:min-h-[690px]">
        <Image src="/images/home-hero.jpg" alt="Children and community served by Ssemuyaba Foundation" fill priority className="object-cover object-center opacity-55" sizes="100vw" />
        <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(3,22,11,.96)_0%,rgba(3,22,11,.82)_43%,rgba(3,22,11,.3)_100%)]" />
        <div className="absolute inset-0 bg-gradient-to-t from-[#03160b] via-transparent to-[#03160b]/30" />
        <div className="about-hero-glow absolute -left-24 top-20 h-80 w-80 rounded-full bg-[#13d74c]/15 blur-3xl" />
        <div className="section-wrap relative z-10 flex min-h-[650px] items-center py-20 lg:min-h-[690px]">
          <div className="max-w-3xl about-reveal">
            <div className="mb-5 flex flex-wrap gap-2"><span className="rounded-full border border-[#86f6a2]/30 bg-white/10 px-4 py-2 text-[10px] font-black uppercase tracking-[.22em] text-[#9bf5b4] backdrop-blur">About Ssemuyaba Foundation</span><span className="rounded-full border border-white/15 bg-black/10 px-4 py-2 text-[10px] font-bold text-white/70 backdrop-blur">Uganda • Africa</span></div>
            <h1 className="max-w-3xl text-5xl font-black leading-[.96] tracking-[-.05em] sm:text-6xl lg:text-[78px]">Love that reaches.<br/><span className="about-gradient-text">Hope that remains.</span></h1>
            <div className="mt-6 h-1.5 w-44 rounded-full bg-gradient-to-r from-[#13d74c] via-[#9bf5b4] to-[#ff1d2d]" />
            <p className="mt-7 max-w-2xl text-base leading-7 text-white/78 sm:text-lg">We are a faith-driven foundation in Uganda committed to empowering vulnerable orphans, children and widows with love, support, education and sustainable opportunities for a better tomorrow.</p>
            <div className="mt-8 flex flex-wrap gap-3"><Link href="/donate" className="inline-flex items-center gap-2 rounded-full bg-[#ff1d2d] px-6 py-3.5 text-sm font-extrabold shadow-[0_14px_35px_rgba(255,29,45,.28)] transition duration-300 hover:-translate-y-1 hover:bg-[#e91424]">Help change a life <HeartIcon className="h-4 w-4"/></Link><a href="#our-story" className="inline-flex items-center gap-2 rounded-full border border-white/25 bg-white/5 px-6 py-3.5 text-sm font-extrabold backdrop-blur transition hover:-translate-y-1 hover:bg-white/10">Discover our story <ArrowRight className="h-4 w-4"/></a></div>
          </div>
        </div>
        <div className="absolute bottom-10 right-5 z-10 hidden w-[310px] rotate-2 overflow-hidden rounded-[1.8rem] border border-white/20 bg-white/10 p-2 shadow-2xl backdrop-blur-md lg:block about-photo-float"><div className="relative h-[205px] overflow-hidden rounded-[1.35rem]"><Image src="/images/food-4.jpg" alt="Community outreach and children" fill className="object-cover" sizes="310px"/></div><div className="flex items-center justify-between px-3 py-3"><span className="text-xs font-black">Serving with love</span><span className="text-[10px] font-bold text-[#9bf5b4]">Uganda</span></div></div>
        <svg className="absolute bottom-[-1px] left-0 z-20 h-[50px] w-full" viewBox="0 0 1200 50" preserveAspectRatio="none" aria-hidden="true"><path d="M0 10 C250 42 950 42 1200 10 L1200 50 L0 50Z" fill="white"/><path d="M0 10 C250 42 950 42 1200 10" fill="none" stroke="#13d74c" strokeWidth="3"/></svg>
      </section>

      <section id="our-story" className="relative py-16 sm:py-24">
        <div className="section-wrap grid items-center gap-12 lg:grid-cols-[.92fr_1.08fr]">
          <div className="about-image-stack relative mx-auto w-full max-w-[540px]"><div className="absolute -left-5 -top-5 h-32 w-32 rounded-full bg-[#13d74c]/10 blur-2xl" /><div className="relative z-10 overflow-hidden rounded-[2rem] shadow-[0_25px_70px_rgba(3,73,31,.16)]"><Image src="/images/food-3.jpg" alt="Children and families receiving support" width={900} height={1100} className="h-[500px] w-full object-cover transition duration-700 hover:scale-[1.03]" /></div><div className="absolute -bottom-7 -right-5 z-20 w-[58%] overflow-hidden rounded-[1.5rem] border-8 border-white shadow-2xl about-photo-float"><Image src="/images/books-2.jpg" alt="Education support for children" width={700} height={500} className="h-40 w-full object-cover" /></div><div className="absolute -left-4 bottom-10 z-20 rounded-2xl bg-[#ff1d2d] px-5 py-4 text-white shadow-xl"><p className="text-2xl font-black">Hope</p><p className="text-[9px] font-bold uppercase tracking-[.18em] text-white/75">in action</p></div></div>
          <div><p className="about-kicker text-[10px] font-black uppercase tracking-[.25em] text-[#087a35]">Who we are</p><h2 className="mt-3 text-3xl font-black leading-tight sm:text-5xl">We don't just see a need.<br/><span className="text-[#087a35]">We see a life worth investing in.</span></h2><p className="mt-6 text-sm leading-7 text-black/65 sm:text-base">Ssemuyaba Foundation exists to empower vulnerable Orphans, Children and Widows in Africa, beginning in Uganda. We provide love, support, education and sustainable opportunities to help vulnerable children and widows build a better tomorrow.</p><p className="mt-4 text-sm leading-7 text-black/65 sm:text-base">Our work is also deeply rooted in faith. We teach and preach the good news of Jesus Christ, the soon-coming King, believing that practical compassion and spiritual hope belong together.</p><div className="mt-7 flex items-start gap-4 rounded-2xl border border-[#d8eee0] bg-[#f1fbf5] p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#087a35] text-white shadow-lg"><HeartIcon className="h-5 w-5"/></span><div><p className="text-sm font-black text-[#063019]">A mission built on dignity.</p><p className="mt-1 text-xs leading-5 text-black/55">Every child deserves to learn, every widow deserves opportunity, and every community deserves hope.</p></div></div></div>
        </div>
      </section>

      <section className="relative overflow-hidden bg-[#f1fbf5] py-16 sm:py-24"><div className="absolute -right-32 top-0 h-96 w-96 rounded-full bg-[#13d74c]/10 blur-3xl" /><div className="section-wrap relative z-10"><div className="mx-auto max-w-3xl text-center"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#087a35]">Why we exist</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Purpose with a <span className="text-[#087a35]">heartbeat.</span></h2><p className="mt-4 text-sm leading-6 text-black/60 sm:text-base">Our purpose is simple: reach people who are often overlooked and help them move toward a future filled with dignity, opportunity and hope.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="about-purpose-card rounded-[1.7rem] bg-white p-7 shadow-[0_12px_40px_rgba(3,73,31,.06)]"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#e4f8eb] text-[#087a35]"><HeartIcon className="h-6 w-6"/></span><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-[#087a35]">Our Purpose</p><h3 className="mt-2 text-2xl font-black">Reach the unreachable.</h3><p className="mt-3 text-sm leading-6 text-black/55">To identify vulnerable children and widows, stand beside them and connect them with practical support and lasting opportunity.</p></article><article className="about-purpose-card rounded-[1.7rem] bg-[#063019] p-7 text-white shadow-[0_18px_50px_rgba(3,73,31,.2)]"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#13d74c] text-[#063019] text-xl font-black">◎</span><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-[#9bf5b4]">Our Mission</p><h3 className="mt-2 text-2xl font-black">Empower vulnerable lives.</h3><p className="mt-3 text-sm leading-6 text-white/65">To provide love, support, education, healthcare, skills and sustainable opportunities while sharing the hope of Christ.</p></article><article className="about-purpose-card rounded-[1.7rem] bg-white p-7 shadow-[0_12px_40px_rgba(3,73,31,.06)]"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#fff0f1] text-[#ff1d2d] text-xl font-black">↗</span><p className="mt-6 text-[10px] font-black uppercase tracking-[.2em] text-[#ff1d2d]">Our Vision</p><h3 className="mt-2 text-2xl font-black">A better tomorrow.</h3><p className="mt-3 text-sm leading-6 text-black/55">A future where vulnerable children and widows are equipped to thrive, communities are strengthened, and the hope of Christ is shared.</p></article></div></div></section>

      <section className="relative py-16 sm:py-24"><div className="section-wrap grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#087a35]">What guides us</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Our core values are not just words.</h2><p className="mt-5 max-w-md text-sm leading-6 text-black/60">They shape how we serve, how we steward support, and how we treat every person entrusted to our care.</p><Link href="/donate" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#087a35] px-6 py-3.5 text-xs font-extrabold text-white shadow-lg transition hover:-translate-y-1 hover:bg-[#063019]">Stand with us <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-4 sm:grid-cols-2">{values.map((v,i)=>{const Icon=v.icon;return <article key={v.title} className="about-value-card group rounded-[1.5rem] border border-black/[.06] bg-white p-6 shadow-[0_10px_35px_rgba(3,73,31,.055)] transition duration-500 hover:-translate-y-2 hover:border-[#b9e6c7] hover:shadow-[0_22px_55px_rgba(3,73,31,.12)]"><div className="flex items-center justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#f1fbf5] text-[#087a35] transition duration-300 group-hover:rotate-3 group-hover:bg-[#087a35] group-hover:text-white">{typeof Icon==="string"?<span className="text-xl font-black">{Icon}</span>:<Icon className="h-6 w-6"/>}</span><span className="text-[10px] font-black text-black/20">0{i+1}</span></div><h3 className="mt-5 text-lg font-black">{v.title}</h3><p className="mt-2 text-xs leading-5 text-black/55">{v.text}</p></article>})}</div></div></section>

      <section className="overflow-hidden bg-[#03160b] py-16 text-white sm:py-24"><div className="section-wrap"><div className="grid items-center gap-12 lg:grid-cols-[1fr_1fr]"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#79f59b]">Our impact</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Where compassion becomes <span className="text-[#13d74c]">action.</span></h2><p className="mt-5 max-w-xl text-sm leading-6 text-white/62">Every program is designed to answer a real need while protecting dignity and opening the door to a more sustainable future.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{impact.map(item=><div key={item.title} className="about-impact-row rounded-2xl border border-white/10 bg-white/[.045] p-4 transition hover:-translate-y-1 hover:bg-white/[.08]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#13d74c] text-[#063019]"><item.icon className="h-5 w-5"/></span><div><h3 className="text-sm font-black">{item.title}</h3><p className="mt-1 text-[10px] leading-4 text-white/50">{item.text}</p></div></div></div>)}</div></div><div className="grid grid-cols-2 gap-3 sm:gap-4"><div className="relative mt-8 overflow-hidden rounded-[1.6rem]"><Image src="/images/books.jpg" alt="Children and education support" width={700} height={850} className="h-[330px] w-full object-cover transition duration-700 hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4"><p className="text-xs font-black">Education</p></div></div><div className="relative overflow-hidden rounded-[1.6rem]"><Image src="/images/health-1.jpg" alt="Healthcare support" width={700} height={850} className="h-[330px] w-full object-cover transition duration-700 hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4"><p className="text-xs font-black">Healthcare</p></div></div><div className="relative overflow-hidden rounded-[1.6rem]"><Image src="/images/food-5.jpg" alt="Food and community support" width={700} height={700} className="h-[250px] w-full object-cover transition duration-700 hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4"><p className="text-xs font-black">Care</p></div></div><div className="relative mt-8 overflow-hidden rounded-[1.6rem]"><Image src="/images/preaching.jpg" alt="Preaching and community outreach" width={700} height={700} className="h-[250px] w-full object-cover transition duration-700 hover:scale-105" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent p-4"><p className="text-xs font-black">Preaching & outreach</p></div></div></div></div></div></section>

      <section className="relative overflow-hidden py-16 sm:py-24"><div className="section-wrap"><div className="grid items-center gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#087a35]">The people behind the mission</p><h2 className="mt-3 text-3xl font-black sm:text-5xl">Children deserve more than survival.</h2><p className="mt-5 text-sm leading-6 text-black/60">They deserve someone who believes in them. They deserve a classroom, a meal, care when they are sick, a safe community and the chance to grow into who they were created to be.</p><p className="mt-4 text-sm leading-6 text-black/60">Your support helps us keep showing up — with practical help, compassionate service and the message of hope we carry through preaching.</p><Link href="/donate" className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#ff1d2d] px-6 py-3.5 text-xs font-extrabold text-white shadow-xl transition hover:-translate-y-1 hover:bg-[#e91424]">Give a child a reason to hope <HeartIcon className="h-4 w-4"/></Link></div><div className="about-collage grid grid-cols-12 gap-3"><div className="col-span-7 overflow-hidden rounded-[1.7rem]"><Image src="/images/food.jpg" alt="Children supported by the foundation" width={900} height={700} className="h-[270px] w-full object-cover transition duration-700 hover:scale-105 sm:h-[340px]" /></div><div className="col-span-5 mt-10 overflow-hidden rounded-[1.7rem]"><Image src="/images/books-2.jpg" alt="Education and children" width={700} height={900} className="h-[220px] w-full object-cover transition duration-700 hover:scale-105 sm:h-[290px]" /></div><div className="col-span-5 -mt-5 overflow-hidden rounded-[1.7rem]"><Image src="/images/food-6.jpg" alt="Community care" width={700} height={700} className="h-[210px] w-full object-cover transition duration-700 hover:scale-105 sm:h-[260px]" /></div><div className="col-span-7 overflow-hidden rounded-[1.7rem]"><Image src="/images/donation.jpg" alt="Giving and empowerment" width={900} height={700} className="h-[250px] w-full object-cover transition duration-700 hover:scale-105 sm:h-[300px]" /></div></div></div></div></section>

      <section className="relative overflow-hidden bg-[#063019] py-16 text-white sm:py-20"><div className="absolute -left-20 -top-32 h-72 w-72 rounded-full border-[45px] border-white/5" /><div className="absolute -right-20 bottom-[-12rem] h-96 w-96 rounded-full bg-[#13d74c]/10 blur-3xl" /><div className="section-wrap relative z-10 text-center"><p className="text-[10px] font-black uppercase tracking-[.25em] text-[#9bf5b4]">You can be part of the story</p><h2 className="mx-auto mt-3 max-w-4xl text-3xl font-black leading-tight sm:text-5xl">Someone's tomorrow can look different because <span className="text-[#13d74c]">you cared today.</span></h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-6 text-white/62">Stand with vulnerable orphans, children and widows in Uganda. Your generosity helps us provide practical support, education, sustainable opportunity and hope through the gospel.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href="/donate" className="inline-flex items-center gap-2 rounded-full bg-[#ff1d2d] px-7 py-4 text-sm font-extrabold shadow-xl transition duration-300 hover:-translate-y-1 hover:bg-[#e91424]">Donate & change a life <HeartIcon className="h-5 w-5"/></Link><Link href="/contact-us" className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/5 px-7 py-4 text-sm font-extrabold transition hover:-translate-y-1 hover:bg-white/10">Talk to us <ArrowRight className="h-4 w-4"/></Link></div></div></section>
    </main>
  );
}
